Attempt to make multicall similar to Solidity Implementation
argentlabs/argent-contracts-starknet pull request #28
Opened 2022-02-10 09:41 UTC by dhruvkelawala

- return block_number along with result_len and result

2022-02-14 13:41 UTC, juniset requested changes
Thanks for your contribution!

To move ahead with this PR please make sure to update the tests in `test/multicall.py`.

2022-02-14 13:41 UTC, juniset commented on contracts/Multicall.cairo
> +func aggregate{syscall_ptr : felt*, range_check_ptr}(calls_len : felt, calls : felt*) -> (
Can you keep the existing formatting to be consistent with the other contracts of the repo?

2022-02-14 16:23 UTC, juniset commented
Also, I've just created the `develop` branch; could you target your PR to that branch?

2022-02-17 16:34 UTC, juniset commented
Closed by #29

2022-02-17 16:34 UTC, closed without merging

2022-02-28 12:46 UTC, dhruvkelawala commented
Sorry I was busy with Jediswap. Good to see that you have included my changes :)